#!/usr/bin/env python
import praw
import sys
r = praw.Reddit('spif-reddit-utils')
if len(sys.argv) < 2:
	print "usage: " + sys.argv[0] + " <subreddit> [number]"
	exit(1)
else:
	sub=sys.argv[1]
if len(sys.argv) == 3:
	postlimit=int(sys.argv[2])
else:
	postlimit=15
posts = r.get_subreddit(sub).get_new(limit=postlimit)
for post in posts:
	print str(post.score) + ' ' + str(post.num_comments) + ' ' + post.id + ' ' + str(post.author) + ' ' + post.title
