#!/usr/bin/env python
import praw
import sys
import getpass
r = praw.Reddit('spif-reddit-utils')
username = raw_input("username [%s]: " % getpass.getuser())
if not username:
        username = getpass.getuser()
password = getpass.getpass()
r.login(username,password)
msgs = r.get_unread()
clear=0
if len(sys.argv) > 1:
	if sys.argv[1] == 'clear':
		clear=1
for msg in msgs:
	print msg.body
	print msg.permalink
	if clear == 1:
		msg.mark_as_read()
