#!/usr/bin/env python
import praw
import sys
import time
import getpass
r = praw.Reddit('spif-reddit-utils')
username = raw_input("username [%s]: " % getpass.getuser())
if not username:
        username = getpass.getuser()
password = getpass.getpass()
r.login(username,password)
if len(sys.argv) < 4:
	print "usage: " + sys.argv[0] + " <post ID> <comment ID> <reply text>"
	exit(1)
s = r.get_submission(submission_id=sys.argv[1])
print str(s.score) + ' ' + str(s.author) + ' ' + s.title
if s.selftext != "":
	print s.selftext
else:
	print s.url
if len(s.comments) > 0:
	print
	flat_comments = praw.helpers.flatten_tree(s.comments)
	for comment in flat_comments:
		if comment.id == sys.argv[2]:
			print "replying to comment:"
			print comment.id + ' ' + str(comment.score) + ' ' + str(comment.author)
			print comment.body
			print "with:"
			print sys.argv[3]
			comment.reply(sys.argv[3])
