#!/usr/bin/env python
import praw
import sys
r = praw.Reddit('spif-reddit-utils')
if len(sys.argv) < 2:
	print "usage: " + sys.argv[0] + " <username>"
	exit(1)
else:
	username=sys.argv[1]
user = r.get_redditor(username)
print "link: " + str(user.link_karma) + " comment: " + str(user.comment_karma)
if len(sys.argv) == 3:
	if sys.argv[2] == 'posts':
		posts = user.get_submitted(sort='new',limit=15)
		for post in posts:
			print str(post.score) + ' ' + str(post.num_comments) + ' ' + post.id + ' ' + post.title
	if sys.argv[2] == 'comments':
		comments = user.get_comments(sort='new',limit=15)
		for comment in comments:
			print comment.parent_id + ' ' + str(comment.score) + ' ' + comment.body
