#!/usr/bin/env python
import praw
import sys
import time
r = praw.Reddit('spif-reddit-utils')
username = raw_input("username [%s]: " % getpass.getuser())
if not username:
        username = getpass.getuser()
password = getpass.getpass()
r.login(username,password)
if len(sys.argv) < 4:
	print "usage: " + sys.argv[0] + " <post ID> <comment ID> [up|down|clear]"
	exit(1)
s = r.get_submission(submission_id=sys.argv[1])
print str(s.score) + ' ' + str(s.author) + ' ' + s.title
if s.selftext != "":
	print s.selftext
else:
	print s.url
if len(s.comments) > 0:
	print
	flat_comments = praw.helpers.flatten_tree(s.comments)
	for comment in flat_comments:
		if comment.id == sys.argv[2]:
			print comment.id + ' ' + str(comment.author) + ' ' + comment.body
			print "old score: " + str(comment.score)
			if sys.argv[3] == 'up':
				print "upvoting comment:"
				comment.upvote()
			if sys.argv[3] == 'down':
				print "downvoting comment:"
				comment.downvote()
			if sys.argv[3] == 'clear':
				print "clearing vote on comment:"
				comment.clear_vote()
	time.sleep(3)
	s = r.get_submission(submission_id=sys.argv[1])
	for comment in flat_comments:
		if comment.id == sys.argv[2]:
			print "new score: " + str(comment.score)
