#!/usr/bin/env python
import praw
import sys
import time
r = praw.Reddit('spif-reddit-utils')
username = raw_input("username [%s]: " % getpass.getuser())
if not username:
        username = getpass.getuser()
password = getpass.getpass()
r.login(username,password)
if len(sys.argv) < 3:
	print "usage: " + sys.argv[0] + " <post ID> [up|down|clear]"
	exit(1)
submission = r.get_submission(submission_id=sys.argv[1])
print str(submission.score) + ' ' + submission.title
if sys.argv[2] == 'up':
	submission.upvote()
if sys.argv[2] == 'down':
	submission.downvote()
if sys.argv[2] == 'clear':
	submission.clear_vote()
time.sleep(10)
submission = r.get_submission(submission_id=sys.argv[1])
print str(submission.score) + ' ' + submission.title
